name: documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Setup Python
          uses: actions/setup-python@v6

        - name: Install local packages to update versions
          run: |
            python -m pip install --upgrade pip uv
            # Manually install CPU-only version of torch so we're not carrying around giant GPU drivers/kernels
            uv pip install --system torch --extra-index-url https://download.pytorch.org/whl/cpu
            uv pip install --system -e "s3torchconnectorclient"
            uv pip install --system -e "s3torchconnector"

        - name: Install dependencies
          run: |
            uv pip install --system sphinx sphinx_rtd_theme sphinx-autoapi ghp-import

        - name: Sphinx build
          run: |
            cd s3torchconnector/docs
            sphinx-build -b html . _build/html

        - name: Import docs
          run: |
            ghp-import -n -p -f s3torchconnector/docs/_build/html
